### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by imarchit19** [imarchit19/game-portal#3]
Set more appropriate favicon.

**Comment by qwerty-rgb** [comment]
okk i'll do it

**Comment by imarchit19** [comment]
I didn't assign it to you.

**Comment by qwerty-rgb** [comment]
i dont want to do it it is a bad and fake repo. i am also gonna report it

**Comment by Ajal333** [comment]
If you don't want to merge it, let it be!

**Comment by imarchit19** [comment]
@qwerty-rgb This is my project and my friends are collaborating on.
Please understand when I say, I am assigning these issues to my juniors and friends new to open source.

**Comment by Eshwar5799** [comment]
I will do this work @imarchit19 ,you can assign this to me.
